Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpiceApp.Data;
using SpiceApp.Utility;

namespace SpiceApp.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }


        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            
            return View(await _db.ApplicationUser.Where(u=>u.Id!=claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpiceApp.Data;
using SpiceApp.Models;
using SpiceApp.Models.ViewModels;
using SpiceApp.Utility;

namespace SpiceApp.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public OrderDetailsCart detailCart { get; set; }

        public CartController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value);
            if (cart != null)
            {
                detailCart.listCart = cart.ToList();
            }
            foreach(var list in detailCart.listCart)
            {
                list.MenuItem = await _db.MenuItem.FirstOrDefaultAsync(m => m.Id == list.MenuItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.price*list.Count);
                if (list.MenuItem.Description.Length > 100)
                {
                    list.MenuItem.Description = list.MenuItem.Description.Substring(0, 99)+"...";
                }
            }

            
            return View(detailCart);
        }

        public async Task<IActionResult> Plus(int cartId)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(c=>c.Id==cartId);
            cart.Count += 1;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Minus(int cartId)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(c => c.Id == cartId);
            if(cart.Count == 1)
            {
                _db.ShoppingCart.Remove(cart);
                await _db.SaveChangesAsync();
                var cnt = _db.ShoppingCart.Where(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
                HttpContext.Session.SetInt32("ssCartCount",cnt);
            }
            else
            {
                cart.Count -= 1;
                await _db.SaveChangesAsync();
            }
            
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(int cartId)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(c => c.Id == cartId);
            _db.ShoppingCart.Remove(cart);
            await _db.SaveChangesAsync();
            var cnt = _db.ShoppingCart.Where(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
            HttpContext.Session.SetInt32("ssCartCount", cnt);
            return RedirectToAction("Index");
        }




        public async Task<IActionResult> Summary()
        {
            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value);
            if (cart != null)
            {
                detailCart.listCart = cart.ToList();
            }
            foreach (var list in detailCart.listCart)
            {
                list.MenuItem = await _db.MenuItem.FirstOrDefaultAsync(m => m.Id == list.MenuItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.price * list.Count);
            }
            ApplicationUser appUser = await _db.ApplicationUser
                .Where(c=>c.Id==claim.Value).FirstOrDefaultAsync();
            detailCart.OrderHeader.PickupName = appUser.Name;
            detailCart.OrderHeader.PhoneNumber = appUser.PhoneNumber;
            detailCart.OrderHeader.PickupTime = DateTime.Now;


            return View(detailCart);
        }



        //Post summary
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


            detailCart.listCart = await _db.ShoppingCart.
                Where(c => c.ApplicationUserId == claim.Value).ToListAsync();

            detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            detailCart.OrderHeader.OrderDate = DateTime.Now;
            detailCart.OrderHeader.UserId = claim.Value;
            detailCart.OrderHeader.Status = SD.StatusSubmitted;
            detailCart.OrderHeader.OrderTotal = 0;
            List<OrderDetails> orderDetailsList = new List<OrderDetails>();

            _db.OrderHeader.Add(detailCart.OrderHeader);
            await _db.SaveChangesAsync();

            
            foreach (var item in detailCart.listCart)
            {
                item.MenuItem = await _db.MenuItem.FirstOrDefaultAsync(m => m.Id == item.MenuItemId);
                OrderDetails orderDetails = new OrderDetails
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = detailCart.OrderHeader.Id,
                    Description = item.MenuItem.Description,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.price,
                    Count = item.Count
                };
                detailCart.OrderHeader.OrderTotal += orderDetails.Price * orderDetails.Count;
                _db.OrderDetails.Add(orderDetails);
            }


            //remove items from shopping card and session
            _db.ShoppingCart.RemoveRange(detailCart.listCart);
            HttpContext.Session.SetInt32("ssCartCount", 0);
            await _db.SaveChangesAsync();

            return RedirectToAction("Confirm","Order",new { id = detailCart.OrderHeader.Id });
        }


        
    }
}

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info">
        <i class="fas fa-plus"></i> &nbsp; Create New
    </a>
</p>

Views/Shared/_IndividualOrderDetails.cshtml
@model SpiceApp.Models.ViewModels.OrderDetailsViewModel
@using SpiceApp.Utility
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.Id" method="post">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%;">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="OrderHeader.Id" />

            <div class="form-group row">
                <div class="col-3">
                    <label>Name</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.Email"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.PhoneNumber"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderTotal"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderDate"></label>
                </div>
                <div class="col-9">
                    <input value="@Model.OrderHeader.PickupDate.ToShortDateString() @Model.OrderHeader.PickupTime.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.Comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>



        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">
                    Order ID:
                </span>
                <span class="badge badge-secondary badge-pill">
                    @Model.OrderHeader.Id
                </span>
            </h4>
            <ul class="list-group mb-3">
                @{ var total = 0.0;}
                @foreach (var details in Model.OrderDetails)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.Name</h6>
                            <small class="text-muted">
                                Quantity : @details.Count
                            </small>
                        </div>
                        <span class="text-muted">
                            @(details.Price * details.Count)
                        </span>
                        @{ total += (details.Price * details.Count);}
                    </li>
                }
                <li class="bg-light list-group-item d-flex justify-content-between">
                    <span class="text-info">
                        Total(USD)
                    </span>
                    <strong class="text-info">
                        $@Model.OrderHeader.OrderTotal
                    </strong>
                </li>
            </ul>
            @if (Model.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDesk)))
            {
                <button type="submit" class="btn btn-success form-control">
                    <i class="far fa-thumbs-up"></i>Confirm PickUp
                </button>
            }
            else
            {
                <button type="submit" disabled class="btn btn-info form-control">
                    @Model.OrderHeader.Status
                </button>
            }

        </div>
    </div>
</form>

Views/Shared/_Layout.cshtml
@using SpiceApp.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpiceApp</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>

<body class="search-background">
    <header>
        
            <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Spice <span class="text-danger">Demo App</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <partial name="_LoginPartial" />
          <ul class="navbar-nav">
              @if (User.IsInRole(SD.ManagerUser))
              {
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Content Managment
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                          <a class="dropdown-item nav-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                          <a class="dropdown-item nav-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                          <a class="dropdown-item nav-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">MenuItem</a>
                          <a class="dropdown-item nav-item" asp-action="Index" asp-controller="User" asp-area="Admin">Users</a>
                      </div>
                  </li>
              }
              @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.CustomerEndUser))
              {
                  <li class="nav-item">
                      <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
                          Order History
                      </a>
                  </li>
              }
              @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.KitchenUser))
              {
                  <li class="nav-item dropdown text-white-50">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Order
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                          <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Manage Order</a>
                          <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order" asp-area="Customer">Order Pickup</a>
                      </div>
                  </li>
              }
              @if (HttpContextAccessor.HttpContext.Session.GetInt32("ssCartCount") != null)
              {
                  <li class="nav-item" style="color:white">
                      <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                          @{
                              var count = HttpContextAccessor.HttpContext.Session.GetInt32("ssCartCount");
                          }
                          <i class="fas fa-shopping-cart"></i>&nbsp;(@count)
                      </a>
                  </li>
              }
              else
              {
                  <li class="nav-item" style="color:white">
                      <a href="#" class="nav-link">
                          <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                      </a>
                  </li>
              }
          </ul>
      </div>
    </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40">
        <div class="container">
            &copy; 2019 - SpiceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/6374d0af9d.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TabbleButtonPartial.cshtml
@model int

    <td style="width:150px">
        <div class="btn-group" role="group">
            <a class="btn btn-primary text-white"
               asp-action="Edit" asp-route-Id="@Model">
                <i class="fas fa-edit"></i>
            </a>
            <a class="btn btn-success text-white"
               asp-action="Details" asp-route-Id="@Model">
                <i class="fas fa-list-alt"></i>
            </a>
            <a class="btn btn-danger text-white"
               asp-action="Delete" asp-route-Id="@Model">
                <i class="fas fa-trash-alt"></i>
            </a>
        </div>
    </td>

Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>



@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach(var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
                <div class="row">
                    <div class="col-md-3 cols-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9"/>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon">@item.Name</label>
                            </div>
                            <div class="col-4 text-right" style="color:maroon;">
                                <h4>$@item.price</h4>
                            </div>
                        </div>
                        
                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@item.Description</p>
                        </div>

                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>
                </div>
            </div>
        }

        <div class="p-4"></div>
    </div>
}