Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SpiceApp.Models
{
    public class MenuItem
    {
        
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public string Spicyness { get; set; }

        public enum Espicy { NA=0,NotSpicy=1,Spicy=2,VerySpicy=3}

        public string Image { get; set; }

        [Display(Name="Category")]
        public int CategoryId { get; set; }
        [Display(Name = "SubCategory")]
        public int SubCategoryId { get; set; }

        [Range(1,int.MaxValue,ErrorMessage ="Price should be greater")]
        public double price { get; set; }

        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
        [ForeignKey("SubCategoryId")]
        public virtual SubCategory SubCategory { get; set; }
    }
}

Areas/Admin/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using SpiceApp.Data;
using SpiceApp.Models;
using SpiceApp.Models.ViewModels;
using SpiceApp.Utility;

namespace SpiceApp.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class MenuItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public MenuItemController(ApplicationDbContext db, IWebHostEnvironment host)
        {
            _db = db;
            _hostingEnvironment = host;
        }
        public IActionResult Index()
        {
            var ItemsList = _db.MenuItem.Include(m => m.Category).Include(m => m.SubCategory).ToList();

            return View(ItemsList);
        }

        //Get - Create
        public IActionResult Create()
        {
            var categoryList = _db.Category.ToList();
            var subCategoryList = _db.SubCategory.Include(m => m.Category).ToList();

            MenuItemAndCategoryViewModel model = new MenuItemAndCategoryViewModel()
            {
                CategoryList = categoryList,
                SubCategoryList = subCategoryList,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MenuItemAndCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var Category = _db.Category.Find(model.MenuItem.CategoryId);
                var SubCategory = _db.SubCategory.Find(model.MenuItem.SubCategoryId);
                MenuItem item = model.MenuItem;
                item.Category = Category;
                item.SubCategory = SubCategory;
                _db.MenuItem.Add(item);
                _db.SaveChanges();

                //Save Image
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var menuItemFromDB = _db.MenuItem.Find(item.Id);
                if (files.Count > 0)
                {
                    //files has been uploaded
                    var uploads = Path.Combine(webRootPath, "images");//all images wiil be int wwwroot/images
                    var extension = Path.GetExtension(files[0].FileName);

                    using (var fileStream = new FileStream(Path.Combine(uploads, item.Id + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    menuItemFromDB.Image = @"\images\" + item.Id + extension;
                }
                else
                {
                    //No files, use default

                    var uploads = Path.Combine(webRootPath, @"images\" + SD.DefaultFoodImage);
                    System.IO.File.Copy(uploads, webRootPath + @"\images\" + item.Id+".png");
                    menuItemFromDB.Image = @"\images\" + item.Id+".png";
                }

                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var categoryList = _db.Category.ToList();
                var subCategoryList = _db.SubCategory.Include(m => m.Category).ToList();

                MenuItemAndCategoryViewModel m = new MenuItemAndCategoryViewModel()
                {
                    MenuItem = model.MenuItem,
                    CategoryList = categoryList,
                    SubCategoryList = subCategoryList,
                };

                return View(m);
            }
        }





        //Get - Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var categoryList = _db.Category.ToList();

            MenuItemAndCategoryViewModel model = new MenuItemAndCategoryViewModel()
            {
                CategoryList = categoryList,
            };
            model.MenuItem = _db.MenuItem.Include(m => m.Category).Include(m => m.SubCategory).SingleOrDefault(m => m.Id == id);
            model.SubCategoryList = _db.SubCategory.Where(s => s.CategoryId == model.MenuItem.CategoryId).ToList();

            if (model.MenuItem == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, MenuItemAndCategoryViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var Category = _db.Category.Find(model.MenuItem.CategoryId);
                var SubCategory = _db.SubCategory.Find(model.MenuItem.SubCategoryId);
                MenuItem item = model.MenuItem;
                item.Category = Category;
                item.SubCategory = SubCategory;
                /*_db.MenuItem.Add(item);
                _db.SaveChanges();*/

                //Save Image
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var menuItemFromDB = _db.MenuItem.Find(item.Id);
                if (files.Count > 0)
                {
                    //Delete orig file
                    var imagePath = Path.Combine(webRootPath, menuItemFromDB.Image.TrimStart('\\'));
                    //Delete old image
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }

                    //upload new image
                    //new images has been uploaded
                    var uploads = Path.Combine(webRootPath, "images");//all images wiil be int wwwroot/images
                    var extension_new = Path.GetExtension(files[0].FileName);

                    using (var fileStream = new FileStream(Path.Combine(uploads, item.Id + extension_new), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    menuItemFromDB.Image = @"\images\" + item.Id + extension_new;
                }

                menuItemFromDB.Name = model.MenuItem.Name;
                menuItemFromDB.Description = model.MenuItem.Description;
                menuItemFromDB.price = model.MenuItem.price;
                menuItemFromDB.CategoryId = model.MenuItem.CategoryId;
                menuItemFromDB.SubCategoryId = model.MenuItem.SubCategoryId;


                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var categoryList = _db.Category.ToList();
                var subCategoryList = _db.SubCategory.Include(m => m.Category).ToList();

                MenuItemAndCategoryViewModel m = new MenuItemAndCategoryViewModel()
                {
                    MenuItem = model.MenuItem,
                    CategoryList = categoryList,
                    SubCategoryList = subCategoryList,
                };

                return View(m);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _db.MenuItem.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            _db.MenuItem.Remove(item);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Areas/Admin/Views/MenuItem/Create.cshtml
@model SpiceApp.Models.ViewModels.MenuItemAndCategoryViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



    <form asp-area="Admin" asp-controller="MenuItem" asp-action="Create" class="col-6" method="post" enctype="multipart/form-data">
        <div class="border backgroundWhite">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
        <div class="form-group">
            <label for="inputItem">Item Name</label>
            <input asp-for="MenuItem.Name" type="text" class="form-control" id="inputItem" placeholder="Enter Item Name">
            <span asp-validation-for="MenuItem.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="inputDescription">Item Description</label>
            <input asp-for="MenuItem.Description" type="text" class="form-control" id="inputDescription" placeholder="Enter Item Description">
        </div>

        <div class="form-group">
            <label for="inputprice">Item Price</label>
            <input asp-for="MenuItem.price" type="text" class="form-control" id="inputprice" placeholder="Enter Item price">
            <span asp-validation-for="MenuItem.price" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="MenuItem.Image"></label>
            <input type="file" name="files" multiple class="form-control"/>
        </div>

        <div class="form-group">
            <label for="categorySelect">Select Category</label>
            <select class="form-control" id="categorySelect" asp-for="MenuItem.CategoryId"
                    asp-items="@(new SelectList(Model.CategoryList,"Id","Name"))">
            </select>
            <label for="ddlCategoryList">Select Sub Category</label>
            <select id="ddlCategoryList" asp-for="MenuItem.SubCategoryId"
                    asp-items="@(new SelectList(Model.SubCategoryList,"Id","Name"))"
                    class="form-control">
            </select>
        </div>


        <button type="submit" class="btn btn-primary">Create</button>
    </form>


@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function updateSubCategoryList() {
            var categorySelected = document.getElementById("categorySelect").value;
            $list = $('#ddlCategoryList');
            $.ajax({
                url: '/Admin/SubCategory/GetSubCategory/' + categorySelected,
                type: 'Get',
                dataType: 'text',
                success: function (data) {
                    results = JSON.parse(data);
                    var categories = "";
                    for (i in results) {
                        categories = categories + ('<option value="' + results[i].value + '">' + results[i].text + '</option>');
                    }
                    $list.empty();
                    $list.append(categories);
                }
            });


        }

        $(document).ready(function () {
            updateSubCategoryList();
        });

        $("#categorySelect").on("change", function () {
            updateSubCategoryList();
        });
    </script>
}

Areas/Admin/Views/MenuItem/Edit.cshtml
@model SpiceApp.Models.ViewModels.MenuItemAndCategoryViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<form asp-area="Admin" asp-controller="MenuItem" asp-action="Edit" class="col-6" method="post" enctype="multipart/form-data">
    <div class="border backgroundWhite">
        <input type="hidden" asp-for="MenuItem.Id"/>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="form-group">
                <label for="inputItem">Item Name</label>
                <input asp-for="MenuItem.Name" type="text" class="form-control" id="inputItem" placeholder="Enter Item Name">
                <span asp-validation-for="MenuItem.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="inputDescription">Item Description</label>
                <input asp-for="MenuItem.Description" type="text" class="form-control" id="inputDescription" placeholder="Enter Item Description">
            </div>

            <div class="form-group">
                <label for="inputprice">Item Price</label>
                <input asp-for="MenuItem.price" type="text" class="form-control" id="inputprice" placeholder="Enter Item price">
                <span asp-validation-for="MenuItem.price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MenuItem.Image"></label>
                <input type="file" name="files" multiple class="form-control" />
            </div>

            <div class="form-group">
                <label for="categorySelect">Select Category</label>
                <select class="form-control" id="categorySelect" asp-for="MenuItem.CategoryId"
                        asp-items="@(new SelectList(Model.CategoryList,"Id","Name"))">
                </select>
                <label for="ddlCategoryList">Select Sub Category</label>
                <select id="ddlCategoryList" asp-for="MenuItem.SubCategoryId"
                        asp-items="@(new SelectList(Model.SubCategoryList,"Id","Name"))"
                        class="form-control">
                </select>
            </div>
        </div>
        <div class="col-3 offset-1">
            <img src="@Model.MenuItem.Image" width="100%" style="border-radius:5px; border: 1px solid #bbb9b9" />
        </div>
    </div>


    <button type="submit" class="btn btn-primary offset-1">Edit</button>
</form>


@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function updateSubCategoryList() {
            var categorySelected = document.getElementById("categorySelect").value;
            $list = $('#ddlCategoryList');
            $.ajax({
                url: '/Admin/SubCategory/GetSubCategory/' + categorySelected,
                type: 'Get',
                dataType: 'text',
                success: function (data) {
                    results = JSON.parse(data);
                    var categories = "";
                    for (i in results) {
                        categories = categories + ('<option value="' + results[i].value + '">' + results[i].text + '</option>');
                    }
                    $list.empty();
                    $list.append(categories);
                }
            });


        }

        $(document).ready(function () {
            updateSubCategoryList();
        });

        $("#categorySelect").on("change", function () {
            updateSubCategoryList();
        });
    </script>
}

Areas/Admin/Views/MenuItem/Index.cshtml
@model IEnumerable<MenuItem>
@{
    ViewData["Title"] = "Items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />

<div class="border backgroundWhite">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Items List</h2>
        </div>
        <div class="col-6 text-right">
            <partial name="_CreateButtonPartial" />
        </div>
    </div>

    <br />
    <div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        @Html.DisplayNameFor(m => m.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Category)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.SubCategory)
                    </th>
                    <th></th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(m => item.price)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(m => item.SubCategory.Name)
                </td>
                <td>
                    <partial name="_TabbleButtonPartial" model="item.Id" />
                </td>
            </tr>
                }
            </table>
        }
        else
        {
            <p>No Items exists...</p>
        }
    </div>
</div>